### ISSUE TITLE
vistio-api-0 pod is in pending state with Istiov1.x

### ISSUE THREAD

**Issue by waytoharish** [nmnellis/vistio#11]
Hi Team,
My vistio pod is in pending state from lo

vistio-api-0                         0/2       Pending   0          24s

~/myIstioTest/vistio$ kubectl logs vistio-api-0 vistio-api
~/myIstioTest/vistio$ kubectl logs vistio-api-0 reloader
~/myIstioTest/vistio$ kubectl describe vistio-api-0
error: the server doesn't have a resource type "vistio-api-0"
~/myIstioTest/vistio$ kubectl logs vistio-api-0 -c reloader

**Comment by nmnellis** [comment]
This is most likely due to your PVC not being filled. You should check to see that they were provisioned

**Comment by waytoharish** [comment]
Please can you tell me what exactly i need to check ??

**Comment by waytoharish** [comment]
my pvc state
vistio-db-vistio-api-0   Pending                                       standard       22h

**Comment by nmnellis** [comment]
you should be able to check the events on your pvc `kubectl describe pvc vistio-db-vistio-api-0 -n <namespace>`.  It appears your pvc is not able to get a volume created

**Comment by waytoharish** [comment]
Warning  ProvisioningFailed  3m (x341 over 1h)  persistentvolume-controller  storageclass.storage.k8s.io "standard" not found

Why this is using class standard.I don't have any class configured

**Comment by nmnellis** [comment]
you need this. Here is an example for aws
```yaml
▶ kubectl get storageclass standard -o yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
```
