### ISSUE TITLE
Configurable Context Root 

### ISSUE THREAD

**Issue by sbueringer** [nmnellis/vistio#7]
Hi,

I'm deploying Istio together with various addons incl. Vistio. Because I didn't want to host all those addons on different hostnames on context root, I tried to deploy Vistio behind an Ingress controller (in this case Traefik) under `/vistio`. The index.html itself is loading but `vizceral.a7cef684b9cd92e564b0.bundle.js` can not be found because of the `/vistio` prefix

Is there any way to configure this?

**Comment by nmnellis** [comment]
I will look to see if this can be done within the vistio web app, in the mean time you should be able to rewrite the url, here is an example on how to do it with nginx. Note `    nginx.ingress.kubernetes.io/rewrite-target: /`

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: vistio-web
  name: vistio-web
spec:
  rules:
  - host: my-subdomain.example.com
    http:
      paths:
      - backend:
          serviceName: vistio-web
          servicePort: http
        path: /vistio
```
