### ISSUE TITLE
Deploying Vistio-API fails with 'PersistentVolumeClaim is not bound: "vistio-db-vistio-api-0" (repeated 4 times)'

### ISSUE THREAD

**Issue by garysu** [nmnellis/vistio#8]
The PVC claim just sits in a pending state and at API doesn't come up successfully, the Web UI just sits there "Loading".

kubectl version shows:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by nmnellis** [comment]
Where is your Kubernetes cluster deployed? Vistio by default assumes that you have a Kubernetes StorageClass named `standard `
Example of mine
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
```
